// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixToolWindowAsyncPackageExample
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackage1String = "44f7531c-e8ac-4cc8-af51-8580f2bac0ef";
        public const string guidVSPackage1CmdSetString = "919cd8f4-e812-4b71-9734-0149032c7c8c";
        public const string guidImagesString = "2eff86d4-3128-459f-aaea-e3093300ba53";
        public static Guid guidVSPackage1 = new Guid(guidVSPackage1String);
        public static Guid guidVSPackage1CmdSet = new Guid(guidVSPackage1CmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
