version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: auSP7uJIC8Y5I0AW97f0ANIOLXxkszux38+nFJhry4PFvH1MBd1xfBFMcA30a8Z9
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
before_build:
    - cmd: nuget restore VsixToolWindowAsyncPackageExample.sln
    - dotnet tool install -g dotnet-sonarscanner
    - dotnet sonarscanner begin /k:"HelloWorldVsixToolWindowAsyncPackageExample" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
build:
    project: VsixToolWindowAsyncPackageExample.sln
    verbosity: minimal
after_build:
     - dotnet sonarscanner end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

#image: Visual Studio 2015
#install:
#- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
#before_build:
 #- ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
 ##- ps: Vsix-TokenReplacement VsixToolWindowAsyncPackageExample\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
#build_script:
 #- nuget restore -Verbosity quiet
 #- msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
#after_test:
 #- ps: Vsix-PushArtifacts | Vsix-PublishToGallery